version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Logging in to Docker...
      - docker login --username lukezirngibl --password k90^ns]eKQ4sV0G{2
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg COMMIT_HASH=$COMMIT_HASH -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"'$IMAGE_REPO_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
